### ISSUE TITLE
ERROR!

### ISSUE THREAD

**Issue by ReLexioN** [rodel77/MiniBoardGames#21]
[16:47:36] [Server thread/ERROR]: Error occurred while enabling MiniBoardGames v2.9.7 (Is it up to date?)
java.lang.NullPointerException
	at me.robin.leaderheads.datacollectors.ck.<init>(ck.java:95) ~[?:?]
	at me.robin.leaderheads.datacollectors.DataCollector.<init>(DataCollector.java:10) ~[?:?]
	at me.robin.leaderheads.datacollectors.OnlineDataCollector.<init>(OnlineDataCollector.java:12) ~[?:?]
	at mx.com.rodel.MBG$1.<init>(MBG.java:254) ~[?:?]
	at mx.com.rodel.MBG.onEnable(MBG.java:254) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by rodel77** [comment]
Cannot reproduce, what leaderheads version are you using?

**Comment by ReLexioN** [comment]
Latest

**Comment by ReLexioN** [comment]
Okey we solved
