### ISSUE TITLE
2.9.9 error

### ISSUE THREAD

**Issue by geumu** [rodel77/MiniBoardGames#22]
[02:56:55] [Server thread/WARN]: [MiniBoardGames] ---- INFO END ----
[02:56:55] [Server thread/WARN]: [MiniBoardGames] An error ocurred using a game, please report it in https://github.com/rodel77/MiniBoardGames/issues (Please send all this info) (More info:)
[02:56:55] [Server thread/WARN]: [MiniBoardGames] Current version: 2.9.9
[02:56:55] [Server thread/WARN]: [MiniBoardGames] Date error: Fri Jun 23 02:56:55 KST 2017
[02:56:55] [Server thread/WARN]: [MiniBoardGames] Error creator: SaeYeon (cab3b202-129a-42fa-ab56-b5fecbed63e0)
[02:56:55] [Server thread/WARN]: [MiniBoardGames] Game: mx.com.rodel.games.defaultgames.uno.UNOGame@65a91d64
[02:56:55] [Server thread/WARN]: [MiniBoardGames] Other info: 172302
[02:56:55] [Server thread/WARN]: java.lang.NullPointerException
[02:56:55] [Server thread/WARN]: 	at mx.com.rodel.games.defaultgames.uno.UNOGame.onPlayerClickOnGUI(UNOGame.java:110)
[02:56:55] [Server thread/WARN]: 	at mx.com.rodel.manager.GameListener.onInventoryClickEvent(GameListener.java:115)
[02:56:55] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor308.invoke(Unknown Source)
[02:56:55] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:56:55] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[02:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[02:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[02:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[02:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[02:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[02:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[02:56:55] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02:56:55] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[02:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[02:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[02:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[02:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[02:56:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:56:55] [Server thread/WARN]: [MiniBoardGames] ---- INFO END ----
[02:56:55] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to MiniBoardGames v2.9.9
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:852) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1411) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_131]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471) ~[?:1.8.0_131]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469) ~[?:1.8.0_131]
	at mx.com.rodel.games.defaultgames.uno.UNOGame.onPlayerLeave(UNOGame.java:62) ~[?:?]
	at mx.com.rodel.games.InventoryGame.onPlayerCloseGUI(InventoryGame.java:229) ~[?:?]
	at mx.com.rodel.manager.GameListener.onInventoryCloseEvent(GameListener.java:149) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor341.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	... 16 more

**Comment by rodel77** [comment]
Fixed in 3.0.0
