### ISSUE TITLE
MiniBoardGames 3.0.0 error

### ISSUE THREAD

**Issue by geumu** [rodel77/MiniBoardGames#23]
[12:32:36] [Server thread/ERROR]: Error occurred while enabling MiniBoardGames v3.0.0 (Is it up to date?)
java.lang.NullPointerException
	at me.robin.leaderheads.datacollectors.b2.b(b2.java:69) ~[?:?]
	at me.robin.leaderheads.datacollectors.b2.<init>(b2.java:75) ~[?:?]
	at me.robin.leaderheads.datacollectors.DataCollector.<init>(DataCollector.java:7) ~[?:?]
	at me.robin.leaderheads.datacollectors.OnlineDataCollector.<init>(OnlineDataCollector.java:72) ~[?:?]
	at mx.com.rodel.MBG$1.<init>(MBG.java:253) ~[?:?]
	at mx.com.rodel.MBG.onEnable(MBG.java:253) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by rodel77** [comment]
Caused by LeaderHeads update to 3.0.1 or disable LeaderHeads Support in config!
