### ISSUE TITLE
SlotMachine bug / Suggestions & Improvements. 

### ISSUE THREAD

**Issue by iLewisMC** [rodel77/MiniBoardGames#28]
Just purchased the plugin and started to mess around with some of the features and ive noticed when using the slotmachine the game just doesnt seem to work at all allowing my to just take items out of the inventory and leaving a "Playing slotmachin" hologram that cant be removed and im getting this error in console:
`[21:54:07 INFO]: iLewisMC issued server command: /games play SlotMachine
[21:54:10 WARN]: java.lang.ClassCastException: Cannot cast java.lang.Double to java.lang.Integer
[21:54:10 WARN]:        at java.lang.Class.cast(Class.java:3369)
[21:54:10 WARN]:        at mx.com.rodel.miniboardgames.configuration.MBGConfiguration.getNode(MBGConfiguration.java:27)
[21:54:10 WARN]:        at mx.com.rodel.miniboardgames.configuration.ConfigurationManager.getGameNode(ConfigurationManager.java:365)
[21:54:10 WARN]:        at mx.com.rodel.miniboardgames.games.InventoryGame.getConfigNode(InventoryGame.java:127)
[21:54:10 WARN]:        at mx.com.rodel.miniboardgames.games.defaultgames.casino.SlotMachine.onGameStart(SlotMachine.java:50)
[21:54:10 WARN]:        at mx.com.rodel.miniboardgames.games.GameRegister.initializeGame(GameRegister.java:200)
[21:54:10 WARN]:        at mx.com.rodel.miniboardgames.MBG.initializeGame(MBG.java:398)
[21:54:10 WARN]:        at mx.com.rodel.miniboardgames.menus.GameRequest.update(GameRequest.java:92)
[21:54:10 WARN]:        at mx.com.rodel.miniboardgames.manager.GameTick.run(GameTick.java:51)
[21:54:10 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[21:54:10 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[21:54:10 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[21:54:10 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[21:54:10 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[21:54:10 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[21:54:10 WARN]:        at java.lang.Thread.run(Thread.java:748)`

Also im not sure if this as where I can suggest features/improvements but; Could you add a button within the invite GUI to select a sort of "skip" action and play single player as its not very obvious to players that they just need to click the send invite button without inviting players to play single player. Also seen as SlotMachine throws an error of 1 max players when you invite people couldnt you make it bypass the invite GUI and go straight into the game? 

Cheers. If I find anymore bugs ill let you guys know.

**Comment by rodel77** [comment]
I don't found your profile in Spigot but i see it in leaks pages, then if you are getting the leaked version please consider buy the plugin it helps me to continue updating the plugin

That error is fixed for next version, and the suggestion will be added to

Cheers

**Comment by iLewisMC** [comment]
That's right, I am a member of many different forums. Am also already a licence premium holder of this plugin. I have a different nick of spigot. Shortly after purchasing the plugin you messaged me wth an offer for a site called Server Locator. 

Thanks for looking into the issue and suggestion:) 
Cheers

**Comment by iLewisMC** [comment]
Jut realised that was for Provotes. Either way I already have purchased this plugin from you :)
