### ISSUE TITLE
Error with Fabolous Fred

### ISSUE THREAD

**Issue by rodel77** [rodel77/MiniBoardGames#3]
[17:35:20 WARN]: [MiniBoardGames] Task #19695036 for MiniBoardGames v2.6.1 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_112]
at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_112]
at mx.com.rodel.games.defaultgames.FabulousFred$1.run(FabulousFred.java:227) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[17:35:21 WARN]: [MiniBoardGames] Task #19695036 for MiniBoardGames v2.6.1 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_112]
at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_112]
at mx.com.rodel.games.defaultgames.FabulousFred$1.run(FabulousFred.java:227) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by rodel77** [comment]
Fixed for MBG 2.6.2
