### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by rodel77** [rodel77/MiniBoardGames#30]
[13:22:54] [Server thread/WARN]: [MiniBoardGames] Error while searching game on GUI '§e§lGiochi da Tavolo'
[13:22:54] [Server thread/WARN]: java.lang.NullPointerException
[13:22:54] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.menus.MenuGame.onSelectItem(MenuGame.java:33)
[13:22:54] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.menulib.InventoryMenu.listenClick(InventoryMenu.java:54)
[13:22:54] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.menulib.InventoryMenuManager.InventoryClickEvent(InventoryMenuManager.java:19)
[13:22:54] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
[13:22:54] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:22:54] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[13:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[13:22:54] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:22:54] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[13:22:54] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[13:22:54] [Server thread/WARN]: [MiniBoardGames] Error while searching game on GUI '§a§lSeleziona Server'
[13:22:54] [Server thread/WARN]: java.lang.NullPointerException
[13:22:54] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.menus.MenuGame.onSelectItem(MenuGame.java:33)
[13:22:54] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.menulib.InventoryMenu.listenClick(InventoryMenu.java:54)
[13:22:54] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.menulib.InventoryMenuManager.InventoryClickEvent(InventoryMenuManager.java:19)
[13:22:54] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
[13:22:54] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:22:54] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[13:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[13:22:54] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:22:54] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[13:22:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[13:22:54] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[13:22:55] [Server thread/WARN]: [MiniBoardGames] Error while searching game on GUI '§a§lSeleziona Server'
[13:22:55] [Server thread/WARN]: java.lang.NullPointerException
[13:22:55] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.menus.MenuGame.onSelectItem(MenuGame.java:33)
[13:22:55] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.menulib.InventoryMenu.listenClick(InventoryMenu.java:54)
[13:22:55] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.menulib.InventoryMenuManager.InventoryClickEvent(InventoryMenuManager.java:19)
[13:22:55] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
[13:22:55] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:22:55] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:22:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[13:22:55] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:22:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:22:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[13:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[13:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[13:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[13:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[13:22:55] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:22:55] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[13:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[13:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[13:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[13:22:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by rodel77** [comment]
Fixed for next update
