### ISSUE TITLE
Some errors 2

### ISSUE THREAD

**Issue by rodel77** [rodel77/MiniBoardGames#31]
[17:37:16] [Server thread/WARN]: [MiniBoardGames] An error ocurred using a game, please report it in https://github.com/rodel77/MiniBoardGames/issues (Please send all this info) (More info:)
[17:37:16] [Server thread/WARN]: [MiniBoardGames] Current version: 3.1.4
[17:37:16] [Server thread/WARN]: [MiniBoardGames] Date error: Thu Aug 17 17:37:16 CEST 2017
[17:37:16] [Server thread/WARN]: [MiniBoardGames] Error creator: egedis (7c388d23-2eb5-3c81-adf2-fded30da997f)
[17:37:16] [Server thread/WARN]: [MiniBoardGames] Game: mx.com.rodel.miniboardgames.games.defaultgames.MasterMind@167ccf5a
[17:37:16] [Server thread/WARN]: java.lang.NullPointerException
[17:37:16] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.manager.GameListener.onInventoryClickEvent(GameListener.java:118)
[17:37:16] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
[17:37:16] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:37:16] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:37:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[17:37:16] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:37:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[17:37:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[17:37:16] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[17:37:16] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[17:37:16] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[17:37:16] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:37:16] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:37:16] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:37:16] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:37:16] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[17:37:16] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[17:37:16] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:37:16] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[17:37:16] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:37:16] [Server thread/WARN]: [MiniBoardGames] ---- INFO END ----

**Comment by rodel77** [comment]
Can't added descriptive error if happend in next version

Please report it if you see it in next update!

**Comment by rodel77** [comment]
Testing discord bot!

**Comment by rodel77** [comment]
Testing discord bot x2

**Comment by rodel77** [comment]
Probably fixed, this is very old...
