### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by aaa8881** [rodel77/MiniBoardGames#36]
https://pastebin.com/Jrg9kwdz
``
[02:42:50] [Server thread/WARN]: java.lang.IllegalArgumentException: text contains invalid characters
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.drawText(MapGame.java:593)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.defaultgames.G2048.Game2048.draw(Game2048.java:78)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.render(MapGame.java:204)
[02:42:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.map.CraftMapView.render(CraftMapView.java:146)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap.a(WorldMap.java:288)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ItemWorldMap.a(ItemWorldMap.java:304)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityPlayer.playerTick(EntityPlayer.java:269)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.F_(PlayerConnection.java:138)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[02:42:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:42:50] [Server thread/WARN]: java.lang.IllegalArgumentException: text contains invalid characters
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.drawText(MapGame.java:593)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.defaultgames.G2048.Game2048.draw(Game2048.java:78)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.render(MapGame.java:204)
[02:42:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.map.CraftMapView.render(CraftMapView.java:146)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap.a(WorldMap.java:288)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ItemWorldMap.a(ItemWorldMap.java:304)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityPlayer.playerTick(EntityPlayer.java:269)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.F_(PlayerConnection.java:138)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[02:42:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:42:50] [Server thread/WARN]: java.lang.IllegalArgumentException: text contains invalid characters
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.drawText(MapGame.java:593)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.defaultgames.G2048.Game2048.draw(Game2048.java:78)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.render(MapGame.java:204)
[02:42:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.map.CraftMapView.render(CraftMapView.java:146)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap.a(WorldMap.java:288)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ItemWorldMap.a(ItemWorldMap.java:304)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityPlayer.playerTick(EntityPlayer.java:269)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.F_(PlayerConnection.java:138)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[02:42:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:42:50] [Server thread/WARN]: java.lang.IllegalArgumentException: text contains invalid characters
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.drawText(MapGame.java:593)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.defaultgames.G2048.Game2048.draw(Game2048.java:78)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.render(MapGame.java:204)
[02:42:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.map.CraftMapView.render(CraftMapView.java:146)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap.a(WorldMap.java:288)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ItemWorldMap.a(ItemWorldMap.java:304)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityPlayer.playerTick(EntityPlayer.java:269)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.F_(PlayerConnection.java:138)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[02:42:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:42:50] [Server thread/WARN]: java.lang.IllegalArgumentException: text contains invalid characters
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.drawText(MapGame.java:593)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.defaultgames.G2048.Game2048.draw(Game2048.java:78)
[02:42:50] [Server thread/WARN]: 	at mx.com.rodel.miniboardgames.games.map.MapGame.render(MapGame.java:204)
[02:42:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.map.CraftMapView.render(CraftMapView.java:146)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:333)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldMap.a(WorldMap.java:288)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ItemWorldMap.a(ItemWorldMap.java:304)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityPlayer.playerTick(EntityPlayer.java:269)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.F_(PlayerConnection.java:138)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[02:42:50] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[02:42:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
``
It might be due to translation. I'll PM translation file link or email if dev is interested in fixing the issue.

**Comment by rodel77** [comment]
Its cause your are using special chars not supported by MC Map Font
You can enable this setting "useChineseMapSystem" in the config file, this will make map font look bit weird but it support all chars

If you go to make a translation better send me a unlisted pastebin through spigot message

Cheers
