### ISSUE TITLE
My player maybe copying item with a bug

### ISSUE THREAD

**Issue by cndaniellee** [rodel77/MiniBoardGames#50]
A player copied a lot of precious items this afternoon, and he made the plugin continuously report errors through constant connection and disconnection. I highly suspect that this is a bug in this plugin, hoping to get support...

[21:41:37] [User Authenticator #224/INFO]: UUID of player OfFtHeKid is 023d0c43-52c2-3eda-a75a-9f3de652b1dc
[21:41:38] [Server thread/INFO]: OfFtHeKid[/111.224.127.28:62221] logged in with entity id 218311 at ([shop]-12.682177489604245, 55.0, -23.288708423779326)
[21:41:55] [Server thread/WARN]: [MiniBoardGames] Task #256 for MiniBoardGames v3.3.12 generated an exception
java.lang.NullPointerException: null
	at xyz.rodeldev.miniboardgames.games.InventoryGame.sendTitleAll(InventoryGame.java:288) ~[?:?]
	at xyz.rodeldev.miniboardgames.games.defaultgames.tictactoe.TicTacToeGame.nextTurn(TicTacToeGame.java:125) ~[?:?]
	at xyz.rodeldev.miniboardgames.games.defaultgames.tictactoe.TicTacToeGame.loop(TicTacToeGame.java:193) ~[?:?]
	at xyz.rodeldev.miniboardgames.manager.GameTick.run(GameTick.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-235]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
[21:41:57] [Server thread/INFO]: OfFtHeKid lost connection: Disconnected

**Comment by rodel77** [comment]
Fixed the error on the last build, not sure about the duplication issue since there is no much more info but I've added better error messages
